# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'C:\Users\David Mitchell\Desktop\Programming\Python\qtPy\MadiRadio UI designer\MadiRadioUI3ChatWindow.ui'
# Created by: PyQt5 UI code generator 5.15.4
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowServer(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindowServer")
        MainWindow.resize(1000, 900)
        MainWindow.setMinimumSize(QtCore.QSize(550, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.serverChatGridLayoud = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.serverChatGridLayoud.setFont(font)
        self.serverChatGridLayoud.setObjectName("serverChatGridLayoud")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.serverChatGridLayoud)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.messageLabel = QtWidgets.QLabel(self.serverChatGridLayoud)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout_2.addWidget(self.messageLabel, 1, 0, 1, 1)
        self.messageField = QtWidgets.QLineEdit(self.serverChatGridLayoud)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.messageField.setFont(font)
        self.messageField.setInputMask("")
        self.messageField.setText("")
        self.messageField.setDragEnabled(True)
        self.messageField.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.messageField.setClearButtonEnabled(True)
        self.messageField.setObjectName("messageField")
        self.messageField.setFocus()
        self.gridLayout_2.addWidget(self.messageField, 1, 1, 1, 1)
        self.send_pushButton = QtWidgets.QPushButton(self.serverChatGridLayoud)
        self.send_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_pushButton.setObjectName("send_pushButton")
        self.send_pushButton.clicked.connect(lambda: self.sendMessage())
        self.gridLayout_2.addWidget(self.send_pushButton, 1, 2, 1, 1)
        self.chatTextBox = QtWidgets.QTextEdit(self.serverChatGridLayoud)
        self.chatTextBox.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.chatTextBox.setLineWidth(3)
        self.chatTextBox.setMidLineWidth(1)
        self.chatTextBox.setReadOnly(True)
        self.chatTextBox.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse| QtCore.Qt.LinksAccessibleByMouse)
        self.chatTextBox.setObjectName("chatTextBox")
        self.gridLayout_2.addWidget(self.chatTextBox, 0, 0, 1, 3)
        self.gridLayout.addWidget(self.serverChatGridLayoud, 3, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(60, 10, 60, 10)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.callPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.callPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.callPushButton.setObjectName("callPushButton")
        self.horizontalLayout.addWidget(self.callPushButton)
        self.videoPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.videoPushButton.setObjectName("videoPushButton")
        self.horizontalLayout.addWidget(self.videoPushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindowServer):
        _translate = QtCore.QCoreApplication.translate
        MainWindowServer.setWindowTitle(_translate("MainWindowServer", "Madi Radio - Server"))
        self.serverChatGridLayoud.setTitle(_translate("MainWindowServer", "Server Chat :"))
        self.messageLabel.setText(_translate("MainWindowServer", "Message:  "))
        self.messageField.setPlaceholderText(_translate("MainWindowServer", "Type something..."))
        self.send_pushButton.setText(_translate("MainWindowServer", "SEND"))
        self.chatTextBox.setHtml(_translate("MainWindowServer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
            "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
            "p, li { white-space: pre-wrap; }\n"
            "</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:700; color:#ffffff;\">Welcome to Madi Radio!</span></p>\n"
            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:700; color:#000000;\">------------------------------</span></p>\n"
            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\"font-size:9pt; font-weight:700;color:#ffffff;\"><br /></span></p></body></html>\n"))
        self.callPushButton.setText(_translate("MainWindowServer", "Call"))
        self.videoPushButton.setText(_translate("MainWindowServer", "Video"))


        MainWindowServer.setStyleSheet('''
            .QMainWindow{
                background-color: rgba(38,8,24,255);
            }
            .QLabel{
                color: white;
            }
            .QPushButton{
                border: 3px solid #440f2b;
                border-style: outset;
                background-color: #4c1130;
                color: white;
                margin-left: 10px;
                margin-right: 10px;
                padding: 5px;
                border-radius: 15px;
            }
            .QPushButton::hover{
                border: 3px solid #6b1e47;
                background-color: #591539;
                color: pink;
            }
        ''')
        self.serverChatGridLayoud.setStyleSheet('''
            .QGroupBox{
                color:white;
            }
            .QTextEdit, ::focus{
                background-color: #761a4a;
                border: 3px solid white;
                border-radius: 15px;
            }
            #messageField{
                color: white;
                border: 3px solid #440f2b;
                background-color: #4c1130;
                padding: 5px,5px;
                padding-left: 10px;
                margin-left: 10%;
                border-radius: 15px;
            }
            #messageField::hover, #messageField::focus{
                border: 3px solid #6b1e47;
                background-color: #591539;
            }

            #send_pushButton{
                border: 3px solid #440f2b;
                border-style: outset;
                background-color: #4c1130;
                color: white;
                padding: 5px;
                padding-left: 10px;
                padding-right: 10px;
                border-radius: 15px;
            }
            #send_pushButton::hover, ::focus{
                border: 3px solid #6b1e47;
                background-color: #591539;
                color: pink;
            }
        ''')
        self.chatTextBox.setStyleSheet('''
        msgBox.my{
            align: right;
            color: green;
        }
        ''')


    def sendMessage(self):
        message = self.messageField.text()
        if message:
            # self.chatTextBox.setReadOnly(False)
            self.displayMessage(message)
            self.messageField.clear()
            self.messageField.setFocus()
            # self.chatTextBox.show()
            # self.chatTextBox.setReadOnly(True)
    def displayMessage(self, message):
        # cursor = QtGui.QCursor.setPos(self.chatTextBox.screen(),-1,-1)
        # self.chatTextBox.setCursor(a0 = cursor )
        self.chatTextBox.insertHtml(f'\n<msgBox class="my" style="color: green;">{message}</msgBox>')

        pass
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowServer()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
